services:
  centos7my57:
    image: centos7my57
    volumes:
      - ./centos7my57/var/lib:/var/lib/mysql
      - ./centos7my57/etc/my.cnf:/etc/my.cnf
    privileged: true
    network_mode: "host"
  centos7my80:
    image: centos7my80
    volumes:
      - ./centos7my80/var/lib:/var/lib/mysql
      - ./centos7my80/etc/my.cnf:/etc/my.cnf
    privileged: true
    network_mode: "host"
  rocky9my84:
    image: rocky9my84
    volumes:
      - ./rocky9my84/var/lib:/var/lib/mysql
      - ./rocky9my84/etc/my.cnf:/etc/my.cnf
    privileged: true
    network_mode: "host"
  rocky9my90:
    image: rocky9my90
    volumes:
      - ./rocky9my90/var/lib:/var/lib/mysql
      - ./rocky9my90/etc/my.cnf:/etc/my.cnf
    privileged: true
    network_mode: "host"
